In [64]:
import pandas as pd
cats=pd.read_csv('tags and categories.csv')
valid_cats=cats[cats['Exclude'].isnull()]
table=pd.pivot_table(valid_cats,values='Tag_Total',index='Contained in',aggfunc='sum')
table.sort_values(by='Tag_Total',ascending=False)

                          Tag_Total
Contained in
Planning                        254
Education                       140
Environment                     121
Uncategorised                    98
Elections / Politics             90
Transport                        81
Economy                          38
Community Services               30
Parks / Recreation               22
Demographics                     16
Public Safety                    15
Community Assets                 13
Housing                          12
Budget / Finance                  9
Health / Human Services           9
Arts / Culture / History          9
Food                              3